#!/bin/bash
# Restart Backend Server Script

echo "🔄 Restarting Backend Server..."
echo ""
echo "⚠️  Please follow these steps manually:"
echo ""
echo "1. Find the terminal running the backend server"
echo "2. Press Ctrl+C to stop it"
echo "3. Run: cd c:/Users/pc/Desktop/Stayza/booking-backend"
echo "4. Run: npm run dev"
echo ""
echo "Or in one line:"
echo "cd c:/Users/pc/Desktop/Stayza/booking-backend && npm run dev"
echo ""
echo "✅ After restart, the following will work:"
echo "   - ✅ /api/realtors/dashboard/stats (date bug fixed)"
echo "   - ✅ /api/realtors/analytics?timeRange=30d"
echo "   - ✅ /api/realtors/revenue-analytics?period=30d"
echo ""
echo "🔐 Then login with:"
echo "   Email: john.realtor@example.com"
echo "   Password: SecurePass123!"
